### ISSUE TITLE
I need to add some data to this application- Barometers

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIO/groundwater#11]
![image](https://user-images.githubusercontent.com/11522897/82571604-6b61b880-9b40-11ea-8da6-ba6b1ea6e0f6.png)

**Once you submit this issue, your data will be reviewed and checked off by the following people (using Github):**
-Product Manager
-Data Manager
-Technical Reviewer (only the text within the database/app: if it's in full sentence format)
-Web Services Manager

**Comment by marthajensen** [comment]
This has been reviewed and checked off by both the data manager and the product manager.

**Comment by marshallrobinson** [comment]
Ok, sounds good. 

@inkenbrandt @marthajensen What is next for this data? Is it presented in the app somewhere already (if so, where?) or does it need to be worked into the app now?

**Comment by marthajensen** [comment]
@marshallrobinson my bad, this data is used for processing. I thought it showed up in the application... We might use it in the future in the app, but its not a priority.
