### ISSUE TITLE
FY '21 Hours

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/groundwater#16]
@inkenbrandt, for the purpose of budgeting, approximately how many hours (if any) are written in for grants for web services in FY '21 for this project? Grant's USGS project is asking for hundreds of hours and I want to make sure you get the amount of time you need for this project as well.

Thanks!

**Comment by inkenbrandt** [comment]
I have Martha in for 90 hours for USGS NGWMN data flow work but that is not entirely related to this project
