### ISSUE TITLE
I have new data to add to the application

### ISSUE THREAD

**Issue by dmenuz** [UGS-GIO/groundwater#18]
@marthajensen @inkenbrandt 

I have data to append to existing tables in the application. The data are all in this folder here:U:\GWP\Wetland\WaterMonitoring\sdeData\2020fall

The data should be appended to the tables with the same names.

I think Paul will need to add some new stations to the monitoring locations table before these data are appended because there are three new stations that were added. Once those stations are added, then we should also link the new stations to the photos that are in the folder referenced above. The first four digits of each photo name corresponds with the AltLocationID for the three new stations.

**Comment by inkenbrandt** [comment]
3 sites have been added and merged into the default database..

**Comment by marthajensen** [comment]
Done
