### ISSUE TITLE
I need to add some data to the database

### ISSUE THREAD

**Issue by inkenbrandt** [UGS-GIO/groundwater#24]
## Description of data you're adding to an existing layer/database
I have added data for our Courthouse Wash and Sevenmile Canyon wells to the `reading` table as to the `barometers` table.  The well ids are 138-141 for late 2020 to March of 2021.  The barometer id is 9066. 

I also added a barometer to the `ugs_ngwmn_monitoring locations table`.  This is number 9060 McIntyre Springs barometer.

All of the changes are in a child version labeled `pinken_edits`.

Please merge the child version into the master.

Thanks!

**Comment by marthajensen** [comment]
Thanks Paul! I will get to this in the next day or so :)

**Comment by marthajensen** [comment]
This is done :).  Please check when you have time
