### ISSUE TITLE
I need to add a domain entry to an existing domain

### ISSUE THREAD

**Issue by inkenbrandt** [UGS-GIO/groundwater#33]
**Description of data you're adding to an existing layer/database**
nrwugspgressp database has a domain labeled `BaroLoggerType`.  We added a new barologger with the `Code` 9020 and the `Description` as Matheson Wetlands 9020.  I am unable to make these changes in the child version I am working on and request that they be made in the master.

**Once you submit this issue, your data will be reviewed and checked off by the following people (using Github):**
-Product Manager
-Data Manager
-Technical Reviewer (only the text within the database/app: if it's in full sentence format)
-Web Services Manager

**Comment by marthajensen** [comment]
done
