### ISSUE TITLE
Unable to see water level graphs and download waterlevel data for the courthouse wash sites

### ISSUE THREAD

**Issue by Stefankirby** [UGS-GIO/groundwater#6]
Unable to see and download data for the courthouse wash sites 138 and 139 in the database.

**Comment by inkenbrandt** [comment]
Browser lags when selecting sites.  Graph never generates.  I checked and am able to download data, but the graph never shows up. I am using https://groundwater-prod.geology.utah.gov/gwdp/ and have checked with Firefox and Chrome

**Comment by marthajensen** [comment]
Unregistered geodatabase tables had caused an issue with ArcGIS Server -- to fix this, I registered two tables and reloaded the data. I think this has been fixed -- 
I checked locationid: 384149109400902  AND 390141113532901

Both graphs generated and I was able to download and view the data.

Those location id's correspond to the Entrada and Navajo - Courthouse Wash sites. Please check the other sites that were causing problems

**Comment by marshallrobinson** [comment]
Also, please make sure to check this on the publicly-shared url:
https://apps.geology.utah.gov/gwdp

The url Paul mentioned in his comment takes you to the same place; however,
that url may go away in the near future.

Thanks

**Comment by marthajensen** [comment]
I was able to graph the data and download the data on the publicly shared URL too (https://apps.geology.utah.gov/gwdp)

I checked the same two Courthouse Wash sites

**Comment by marthajensen** [comment]
FIXED
