### ISSUE TITLE
I need to add some data to this application- Manual table

### ISSUE THREAD

**Issue by marthajensen** [UGS-GIO/groundwater#7]
**Description of data you're adding to an existing layer/database**
Manual measurements for the CHWNAV site

**Once you submit this issue, your data will be reviewed and checked off by the following people (using Github):**
-Product Manager
-Data Manager
-Technical Reviewer (only the text within the database/app: if it's in full sentence format)
-Web Services Manager

**Comment by marthajensen** [comment]
Stefan K's Manual data has been added for site CHWNAV -- please have a look at the application...

**Comment by marshallrobinson** [comment]
@marthajensen, who needs to look at the application? Has this new data been vetted and approved?

**Comment by marthajensen** [comment]
@marshallrobinson that's a good question.  I need to go over the code and figure out where it shows up in the application because neither me nor @StefanKirby are sure.

**Comment by marthajensen** [comment]
Not sure where the data shows up in the application, but I send Stefan an email with a snapshot of the table showing that his new data was there
